# Generated by Django 4.0.1 on 2022-01-26 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoSketch', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Works',
            new_name='Work',
        ),
    ]
