# Generated by Django 4.0.1 on 2022-01-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoSketch', '0002_rename_works_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='work',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
