# Generated by Django 4.0.1 on 2022-02-01 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoSketch', '0003_work_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='user',
        ),
    ]
